### ISSUE TITLE
Query Error: Conversion Error from Double to Float

### ISSUE THREAD

**Issue by rentasad** [CraZySacX/node-jdbc#131]
Hi,

I have a simple query:

**SELECT * FROM F01\\LAGER\\V2LA1001 WHERE NUMMER='65001'**

If I want to get the result, I get the following error:

> dbc:extendedsystems:advantage://192.168.111.30:6262/vs4/VS/DG/VC2;LockType=proprietary;CharType=OEM;TableType=cdx
> USING CONNECTION: 17220297-2251-45d1-9803-217c26ff3f4e
> /home/mst/development/projects/restserver/node_modules/jdbc/lib/resultset.js:107
>                 result[cmd.label] = self._rs['get' + type + 'Sync'](i);
>                                                                    ^
> 
> Error: Error running instance method
> com.extendedsystems.jdbc.advantage.ADSException: [iAnywhere Solutions][Advantage JDBC]Converting from Double to Float.
> 	at com.extendedsystems.jdbc.advantage.q.try(Unknown Source)
> 	at com.extendedsystems.jdbc.advantage.q.case(Unknown Source)
> 	at com.extendedsystems.jdbc.advantage.m.try(Unknown Source)
> 	at com.extendedsystems.jdbc.advantage.ADSResultSet.getFloat(Unknown Source)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 
>     at Error (native)
>     at /home/mst/development/projects/restserver/node_modules/jdbc/lib/resultset.js:107:68
>     at arrayEach (/home/mst/development/projects/restserver/node_modules/lodash/index.js:1289:13)
>     at Function.<anonymous> (/home/mst/development/projects/restserver/node_modules/lodash/index.js:3345:13)
>     at /home/mst/development/projects/restserver/node_modules/jdbc/lib/resultset.js:91:15
>     at Object.async.whilst (/home/mst/development/projects/restserver/node_modules/async/lib/async.js:763:13)
>     at /home/mst/development/projects/restserver/node_modules/jdbc/lib/resultset.js:81:15
>     at /home/mst/development/projects/restserver/node_modules/jdbc/lib/resultsetmetadata.js:12:14

If my Query dont contain float or double, I don't get the error.
I hope you could understand the issue to resolve then?
Best regards

Matthias

**Comment by rentasad** [comment]
I resolved this Problem for me with Changing Type Definitions in resultset.js Line 36
```
    /*
    12.04.2017 CHANGE NUMERIC to DOUBLE to resolve Converting FromDouble to Float Exception...
     */
    typeNames[java.getStaticFieldValue("java.sql.Types", "NUMERIC")]  = "Double";
```

best regards

Matthias
