### ISSUE TITLE
process.dlopen  access denied

### ISSUE THREAD

**Issue by Nocturnal316** [CraZySacX/node-jdbc#149]
I'm attempting to compile/ run an express.js project on windows 7 using java 1.8 . unfortunatly im running into the following error

```
λ node .
module.js:653
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Access is denied.
\\?\D:\APIs\SRA\node_modules\java\build\Release\nodejavabridge_bindings.node
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\APIs\SRA\node_modules\java\lib\nodeJavaBridge.js:21:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

Does anyone have an idea of what needs to be done to fix this issue?

**Comment by CraZySacX** [comment]
You may want to re-open this issue in the https://github.com/joeferner/node-java repository, as it's a failure in that dependency.

When you ran `npm install` did it succeed?   I'm wondering if the `node-java` dependency failed to build correctly.

**Comment by CraZySacX** [comment]
Also saw this as possible solution:

>  FIX : Searched online about updating JAVA_HOME and adding the path of jvm.dll to PATH.

**Comment by Nocturnal316** [comment]
Yea I think it has something to do with Windows Paths and 7 especially.  My Linux box works and my Windows 10 works.

**Comment by CraZySacX** [comment]
Closing as this is an error building a dependency (and it looks as if it's working on other platforms). If this is still an issue, please open a ticket in the [node-java](https://github.com/joeferner/node-java) project.
