### ISSUE TITLE
Will not install on ubuntu 18

### ISSUE THREAD

**Issue by noahc66260** [CraZySacX/node-jdbc#192]
I've tried installing this on a clean ubuntu 18 installation and I cannot get it to build. I have the same problems on other Ubuntu machines I've tried to install this on.
Ubuntu 18.04.1 LTS
node v10.14.2
npm 6.5.0
javac 10.0.2
python 2.7.15.rc1

  SOLINK_MODULE(target) Release/obj.target/nodejavabridge_bindings.node
/usr/bin/ld: cannot find -ljvm
collect2: error: ld returned 1 exit status
nodejavabridge_bindings.target.mk:143: recipe for target 'Release/obj.target/nodejavabridge_bindings.node' failed
make: *** [Release/obj.target/nodejavabridge_bindings.node] Error 1
make: Leaving directory '/home/ubuntu/node-jdbc/node_modules/java/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-1021-aws
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/node-jdbc/node_modules/java
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.9.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-12-18T13_24_11_406Z-debug.log

Is there a work around for this?

**Comment by albanm** [comment]
Getting this error too.

It looks like [something was fixed](https://github.com/joeferner/node-java/issues/436) in node-java 0.10 but this module still uses the 0.9. Is it possible to upgrade the dependency ?

**Comment by albanm** [comment]
FYI I just forked the project and published @albanm/jdbc on npm to try the fix. It seems that upgrading node-java does the trick and all the tests from this project pass.

Anybody can feel free to use @albanm/jdbc, but I do not intend to maintain it, I just hope that this project will be upgraded soon.
