### ISSUE TITLE
../src/java.h:7:10: fatal error: 'jni.h' file not found

### ISSUE THREAD

**Issue by paulomcnally** [CraZySacX/node-jdbc#2]
```
node-gyp rebuild

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:2:
../src/java.h:7:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^
1 error generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/paulomcnally/Documents/bitbucket/teamSER/ser-web-api/node_modules/jdbc/node_modules/java
gyp ERR! node -v v0.10.18
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

Process finished with exit code 1 at 21:08:35.
Execution time: 9,998 ms.
```

**Comment by rahulkathet** [comment]
Not working

**Comment by bodas80** [comment]
For anyone wondering it is due to Java JDK not installed on the machine. What I did is `brew install java` and followed all the steps. It seems to work normally after that.
