### ISSUE TITLE
IBM's BigSQL not connecting

### ISSUE THREAD

**Issue by scottlabs** [CraZySacX/node-jdbc#32]
Hi,

I'm able to connect to IBM's BigSQL using SquirrelSQL, but using node-jdbc throws this error:

```
java.lang.NoClassDefFoundError: org/apache/hive/service/cli/thrift/TCLIService$Iface
        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
        at java.sql.DriverManager.getConnection(DriverManager.java:579)
        at java.sql.DriverManager.getConnection(DriverManager.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
Caused by: java.lang.ClassNotFoundException: org.apache.hive.service.cli.thrift.TCLIService$Iface
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 7 more
] cause: {} }
```

This is the error that jdbc.open returns. I thought this was related to the multiple jars issue referenced elsewhere, but I am adding all .jars to java.classpath like so:

        java.classpath.push('./path/to/jar');

Immediately before calling jdbc.initialize.

Is there something else I'm overlooking entirely? IBM's documentation is difficult to parse.

**Comment by scottlabs** [comment]
Never mind; I was not adding jar files correctly to the class path.

**Comment by lynnfi** [comment]
I meet this problem too,any idea?
