### ISSUE TITLE
Unsupported Driver?

### ISSUE THREAD

**Issue by natdm** [CraZySacX/node-jdbc#74]
Getting the following error:

        > node Connect.js
    { [Error: Could not find class com.sybase.jdbc3.jdbc.SybDriver
        java.lang.NoClassDefFoundError: com/sybase/jdbc3/jdbc/SybDriver
        Caused by: java.lang.ClassNotFoundException: com.sybase.jdbc3.jdbc.SybDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ] cause: nodeJava_java_lang_NoClassDefFoundError {} }
    { [Error: Error running static method
        java.sql.SQLException: No suitable driver found for [omitted]
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
    ] cause: nodeJava_java_sql_SQLException {} }

I've downloaded jconn3.jar and placed it in the same folder as this script. I've used exact path and './' to connect it but I just get the above error.

This works with the same connection settings in RazorSql.

**Comment by CraZySacX** [comment]
What does your connection properties look like?

Make sure you include the ```drivername``` property.  Java can't automatically find the driver class for older drivers.

**Comment by natdm** [comment]
var libpath =       '/Users/[user]/Documents/www/Selenium/Database/jconn3.jar';
    var drivername =    'com.sybase.jdbc3.jdbc.SybDriver';
    var url =           [same url as Razorsql and other apps];
    var user =          [omitted];
    var password =      ' [omitted];

I also set the min/max poolsize to 10/100, and have an empty properties object.

**Comment by natdm** [comment]
I fixed it by adding the user and password to a properties object within the configuration object - had to look at the code. Examples straight out of NPM are out of date I guess.
