### ISSUE TITLE
Upgrade 0.0.13-->0.1.16: config is undefined

### ISSUE THREAD

**Issue by veve90** [CraZySacX/node-jdbc#77]
Hello,

I wanted to upgrade to 0.1.16. However, I do not understand why the URL is not taken.

```
var nodeunit = require('nodeunit');
var jinst = require('../static/js/lib/jinst');
var Pool = require('../static/js/lib/pool');

if (!jinst.isJvmCreated()) {
    jinst.addOption("-Xrs");
    jinst.setupClasspath([IMPALA_JAR_HOME + "hive-service-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "hive-exec-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "libfb303-0.9.2.jar",
        IMPALA_JAR_HOME + "hive-jdbc.jar",
        IMPALA_JAR_HOME + "hive-serde-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "hive-metastore-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "libthrift-0.9.2.jar",

        IMPALA_JAR_HOME + "log4j.jar",
        IMPALA_JAR_HOME + "slf4j-api.jar",
        IMPALA_JAR_HOME + "commons-logging-1.1.3.jar",
        IMPALA_JAR_HOME + "httpclient-4.2.5.jar",
        IMPALA_JAR_HOME + "hadoop-common.jar",
        IMPALA_JAR_HOME + "httpcore-4.2.5.jar",
        IMPALA_JAR_HOME + "hive-jdbc.jar"]);
}

var config = {
    url: 'jdbc:hive2://' + my_impala_host_ip+ '/;auth=noSasl',
    user : 'username',
    password: 'userpass',
    minpoolsize: 2,
    maxpoolsize: 3
};

module.exports = {
    runQuery: function(query, callback){
        sebPool = new Pool(config);
```

The error ():
```
/path/to/project/website/node_modules/jdbc/lib/pool.js:27
  this._url = config.url;
                    ^
TypeError: Cannot read property 'url' of undefined
    at JDBC.Pool (/path/to/project/website/node_modules/jdbc/lib/pool.js:27:21)
    at new JDBC (/path/to/project/website/node_modules/jdbc/lib/jdbc.js:6:8)
    at Object.<anonymous> (/path/to/project/website/routes/index.js:8:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path/to/project/website/app.js:67:35)

```
The url that I have in config is the url that I used for the version 0.0.13..

Thank you!

Alina

**Comment by CraZySacX** [comment]
I'll need to see more of the code where you are setting up the pool.   The error you are getting shows that the config object is undefined (not set properly in the pool object).  Below is a sample of how to setup the pool.  Ensure the config object is defined when you give it to the Pool constructor.

```
setUp: function(callback) {
    if (testpool === null) {
      testpool = new Pool(config);
    }
    callback();
  },
```

**Comment by CraZySacX** [comment]
Closing.  Feel free to reopen if the suggested solution didn't work.
