### ISSUE TITLE
Upgrade 0.0.13-->0.1.16: No suitable driver

### ISSUE THREAD

**Issue by veve90** [CraZySacX/node-jdbc#78]
Hello,

I tried to upgrade from my old node 0.0.13 old JDBC to the new 0.1.6 verison.
However, even though I used the same drivers (I putted them in jinst), 
I have a java.sql.SQLException: No suitable driver found for jdbc:hive2://<IP>:21050/;auth=noSasl

```
var _ = require('lodash');
var IMPALA_JAR_HOME = __dirname + "/../lib/jars/";
var nodeunit = require('nodeunit');
var jinst = require('../static/js/lib/jinst');
var Pool = require('../static/js/lib/pool');

if (!jinst.isJvmCreated()) {
    jinst.addOption("-Xrs");
    jinst.setupClasspath([IMPALA_JAR_HOME + "hive-service-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "hive-exec-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "libfb303-0.9.2.jar",
        IMPALA_JAR_HOME + "hive-jdbc.jar",
        IMPALA_JAR_HOME + "hive-serde-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "hive-metastore-1.1.0-cdh5.4.2.jar",
        IMPALA_JAR_HOME + "libthrift-0.9.2.jar",

        IMPALA_JAR_HOME + "log4j.jar",
        IMPALA_JAR_HOME + "slf4j-api.jar",
        IMPALA_JAR_HOME + "commons-logging-1.1.3.jar",
        IMPALA_JAR_HOME + "httpclient-4.2.5.jar",
        IMPALA_JAR_HOME + "hadoop-common.jar",
        IMPALA_JAR_HOME + "httpcore-4.2.5.jar",
        IMPALA_JAR_HOME + "hive-jdbc.jar"]);
}

var config = {
    url: 'jdbc:hive2://' + constants.IMPALA_HOST + '/;auth=noSasl',
    user : 'myuser',
    password: 'mypass',
    minpoolsize: 2,
    maxpoolsize: 3
};

module.exports = {
    runQuery: function(query, callback){
        myPool = new Pool(config);
        myConn = null;
        myPool.initialize(function(err){
           if(err){
               console.log(err);
           } else{
               myPool.reserve(function(err, myConn) {
                   if(err){
                       console.log(err);
                   }else {

                       // reserve connection
                       myConn.createStatement(function (err, statement) {
                           if (err) {
                               callback(err);
                           } else {
                               statement.executeQuery(query, function (err, resultset) {
                                   if (err) {
                                       callback(err)
                                   } else {
                                       // Convert the result set to an object array.
                                       resultset.toObjArray(function (err, results) {
                                           if (results.length > 0) {
                                               console.log("ID: " + results[0].ID);
                                           }
                                           callback(null, resultset);
                                       });
                                   }
                               });
                           }
                       });


                       // release connection
                       myPool.release(myConn, function(err) {
                           if(err){
                               console.log(err);
                           }
                       });
                   }
               });
           }
        });


    },


```

My ERROR:
```
{ [Error: Error running static method
java.sql.SQLException: No suitable driver found for jdbc:hive2://<IP>:21050/;auth=noSasl
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
] cause: {} }

```

**Comment by CraZySacX** [comment]
Try adding the ```drivername``` property to your config.

Something like:

```javascript
var config = {
    drivername: 'org.apache.hive.jdbc.HiveDriver',
    url: 'jdbc:hive2://' + constants.IMPALA_HOST + '/;auth=noSasl',
    user : 'myuser',
    password: 'mypass',
    minpoolsize: 2,
    maxpoolsize: 3
};
```

If the Hive JDBC driver isn't JDBC 4.0 compatible, then the drivername is still required so that ```Class.forName()``` can be called to load it into the JVM.   See [here](https://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html) for more details.

**Comment by veve90** [comment]
Thank you! The drivername config was the problem!

**Comment by wiichog** [comment]
Hi I'm a little lost with the implementation of HDBC for hive connection do you think you could help me?
